# Generated by Django 3.2.12 on 2022-02-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_priority',
            field=models.CharField(default='Low', max_length=10),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
