# Generated by Django 3.2.12 on 2022-02-28 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_baseballstat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='ProductItem',
        ),
    ]
